### ISSUE TITLE
Django 2.x Support

### ISSUE THREAD

**Issue by MA-Heshmatkhah** [chrisspen/django-chroniker#147]
Would you please add Django 2.x support to your package?
I see that there was a merge request about that, but the PyPI package is not compatible with Django 2.1.7.

**Comment by Menda** [comment]
Hi. I'd say that after merging https://github.com/chrisspen/django-chroniker/pull/151 it would be possible to have a new release that will set fully compatibility. You can try meanwhile to install the package from master.

**Comment by chrisspen** [comment]
I've released a new version.
