### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by mschiegg** [chrisspen/django-chroniker#198]
I have upgraded to Python 3.8.    
Now Chroniker throw an Error on every Job

**AttributeError**
**chroniker/utils.py in __init__ at line 280**
`module 'time' has no attribute 'clock'`

```
daemon = True    
def __init__(self, max_seconds, time_type=c.MAX_TIME, fout=None, check_freq=1, *args, **kwargs):
        super(TimedProcess, self).__init__(*args, **kwargs)
        self.fout = fout or sys.stdout
        self.t0 = time.clock()
        self.t0_objective = time.time()
        self.max_seconds = float(max_seconds)
        self.t1 = None
        self.t1_objective = None
        # The number of seconds the process waits between checks.
```

**Comment by mschiegg** [comment]
I think this should work.  
    
_time.clock is depraceted since Python 3.3 and removed in 3.8_
Replace time.clock() function with time.process_time()
 chroniker/utils.py in init at line 280

**Comment by prlj13** [comment]
If that's the only problem, it looks like a really easy fix. Any chance of it being taken care of soon? Chroniker isn't working for me because we're using Python 3.8

**Comment by mschiegg** [comment]
> If that's the only problem, it looks like a really easy fix. Any chance of it being taken care of soon? Chroniker isn't working for me because we're using Python 3.8

Currently I have no other problems with 3.8
