### ISSUE TITLE
Capturing job exceptions with e.g. Sentry

### ISSUE THREAD

**Issue by synotna** [chrisspen/django-chroniker#22]
I use Sentry ( https://getsentry.com/welcome/ ) to track exceptions, but chroniker handles exceptions from jobs itself before they reach the Sentry/raven code that sends them

I'm wondering how best to fix this:

1. Wrap the code of every management command in try/except and explicitly call Sentry in except - ugly!

2. Monkey patch Job.handle_run - also ugly!

3. Have an option to not handle the exceptions, probably per job - ugly, if not impossible due to the clean up code needed if the job fails

4. Have chroniker run the job through the shell - that way the exception would be in it's own process and not effect the chroniker process, but probably ugly and creates more problems

5. Have chroniker detect if sentry is installed, and pass the exception to it - I think this is the best solution, and could be extended to support other systems

Do you agree, and if so, how would you prefer it be implemented? Create a handle_exception() function in utils to pass errors to, with a function for each exception handling software to check if it's installed and pass exceptions to it?

**Comment by chrisspen** [comment]
I've added a setting to allow specifying a custom error callback function in https://github.com/chrisspen/django-chroniker/commit/a6ac0cf68cd39e5937d4a0f7e066e73f627cdedd.
