### ISSUE TITLE
Viewing Jobs in Admin causes ValueError

### ISSUE THREAD

**Issue by citadelgrad** [chrisspen/django-chroniker#26]
I'm using the 0.6.7 version of the library and Django 1.6.5.

As you can see from the output below the obj.next_run returns a native datetime which raises "ValueError: astimezone() cannot be applied to a naive datetime". 

Here is an image of this output: https://www.evernote.com/shard/s27/sh/a5470979-8bde-438a-9379-25abd2d83006/b305f3fd01372915a68cbc40b2f75a5d

File "/Users/scott/.virtualenvs/gmp/lib/python2.7/site-packages/chroniker/admin.py", line 279, in get_timeuntil
value = capfirst(dateformat.format(timezone.localtime(obj.next_run), format))
[console ready]
>>> obj.next_run
datetime.datetime(2014, 8, 12, 2, 33, 34)

File "/Users/scott/.virtualenvs/gmp/lib/python2.7/site-packages/django/utils/timezone.py", line 261, in localtime
value = value.astimezone(timezone)
[console ready]
>>> timezone
<DstTzInfo 'US/Eastern' LMT-1 day, 19:04:00 STD>
>>> 
ValueError: astimezone() cannot be applied to a naive datetime

**Comment by chrisspen** [comment]
Thanks for the report. I've been able to reproduce this in a unittest. I'll fix this in the next release.

**Comment by chrisspen** [comment]
I've fixed this in the 0.8.1 release.
