### ISSUE TITLE
Freezing entire chroniker

### ISSUE THREAD

**Issue by steffenmandrup** [chrisspen/django-chroniker#31]
Got an issue where a job seems to stall and then freezes entire django-chroniker so no jobs will run untill it it times out after ~8 hours.

Jobs will just be listed as "Due" but are unable to run untill the job that is stuck with is_fresh =False gets removed.

**Comment by steffenmandrup** [comment]
Fixed

**Comment by chrisspen** [comment]
What was the issue?
