### ISSUE TITLE
Error downloading stdout/stderr logs in Django 1.7

### ISSUE THREAD

**Issue by MattTW** [chrisspen/django-chroniker#33]
Admin receives error: __init__() got an unexpected keyword argument 'mimetype'

when attempting to download stdout/stderr log files when running Django 1.7

Quick fix is to change the named argument 'mimetype' on line 583 and 592 in chroniker/admin.py to 'content_type'

BTW, Nice work on chroniker - very useful!

Thanks,
Matt

**Comment by chrisspen** [comment]
Thanks for the report. Yeah, I didn't notice that deprecation.
