### ISSUE TITLE
problem with migrate

### ISSUE THREAD

**Issue by webpioneer** [chrisspen/django-chroniker#35]
After a fresh install of django-chroniker using pip install django-chroniker, and adding it to INSTALLED_APPS. when i run python manage.py migrate, i get the following error:

@transaction.commit_manually
AttributeError: 'module' object has no attribute 'commit_manually'

pip install will automatically install django 1.8.

What version of Django would you recommend installing django-chroniker with ?

**Comment by chrisspen** [comment]
This is a duplicate of #34. This should now be fixed in version 0.8.0.
