### ISSUE TITLE
Stdout and sdterr are shown as bytes instead of strings in emails

### ISSUE THREAD

**Issue by noisy** [chrisspen/django-chroniker#53]
This is an output of `ls -la`:

![selection_069](https://cloud.githubusercontent.com/assets/201263/14984971/b1b0a424-1145-11e6-9f43-dbd4402c4a84.png)

For sure this is a matter of encoding. When I found that problem, I applied a solution founded [here](http://stackoverflow.com/questions/606191/convert-bytes-to-a-python-string).

https://github.com/noisy/django-chroniker/commit/b55a08750a2ef4011e0e1ad06d0bb37b57f4b179

It works as expected:

![selection_070](https://cloud.githubusercontent.com/assets/201263/14985092/2197d80c-1146-11e6-9d71-bf8fbef23a4b.png)

However later I tried to find why those outputs are bytes in the first place.

I found that this commit https://github.com/noisy/django-chroniker/commit/5b21abbe4ea5f67e91143ed538284a8d0a1bfc8a also solve this issue.

I am not sure, why that code was added in the first place, so I need your suggestion @chrisspen  which fix is better.

**Comment by chrisspen** [comment]
Assuming you're using Python3, I believe file objects return byte strings now by default.

Commit https://github.com/noisy/django-chroniker/commit/b55a08750a2ef4011e0e1ad06d0bb37b57f4b179 is probably the better fix.
