### ISSUE TITLE
Error when using chroniker in a project that has disabled the 'delete_selected' action site-wide

### ISSUE THREAD

**Issue by pedfercue** [chrisspen/django-chroniker#60]
If the 'delete_selected' action is disabled site-wide deleting it from the dictionary of actions raises an exception. If we simply checked if 'delete_selected' is in the get_actions return dictionary before deleting it we would prevent this error from happening.

The code can be find at line 680 of the file chroniker/admin.py

**Comment by chrisspen** [comment]
Thanks for the bug report. This has been fixed.
