### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by christianbundy** [chrisspen/django-chroniker#61]
Hey Chris! I noticed that the latest version in PyPi is still 0.8.5, but the version in GitHub is 0.9.2. Do you do regular package updates, or should we be building from source? Thanks!

**Comment by chrisspen** [comment]
I was waiting on some feedback on some recent commits, but as everything
looks fine, I'll be pushing a release up to pypi shortly.

**Comment by chrisspen** [comment]
I've uploaded release 0.9.2 to PyPI.

**Comment by christianbundy** [comment]
Thanks!
