### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by tlaziuk** [chrisspen/django-chroniker#62]
Hello,

when running the `chroniker -e ...` cli command with `python3` we can see a message like this:
```
Traceback (most recent call last):
  File "/usr/bin/chroniker", line 61, in <module>
    execfile(virtualenv, dict(__file__=virtualenv))
NameError: name 'execfile' is not defined
```
To make it works with `python3` I just replaced the `execfile` function with `exec` function according to this: http://stackoverflow.com/a/6357418/1732775

**Comment by chrisspen** [comment]
Added a patch. Unfortunately, I don't personally use that script with Python3, and don't have a good way to test. Please let me know if that fixes your issue.

**Comment by tlaziuk** [comment]
The patch is working, thanks!
