### ISSUE TITLE
Fail with BaseCommand.options_list in django 1.10

### ISSUE THREAD

**Issue by darkwizz** [chrisspen/django-chroniker#64]
Hello, I have a problem with chroniker in django 1.10. When I try to run job I get error:
"type object 'BaseCommand' has no attribute 'option_list'" in 
chroniker/management/commands/cron.py", line 258, in Command
    option_list = BaseCommand.option_list + (

Can somebody help?

Thanks

**Comment by chrisspen** [comment]
This is a known issue. Django 1.10 introduced some backwards incompatible changes that I've not yet upgraded the package to handle.

**Comment by darkwizz** [comment]
so I need to go on django older version, use some another library or make pull-request?

**Comment by chrisspen** [comment]
Yep, I have unittests to check up to Django 1.9. [The issue](http://stackoverflow.com/questions/35181133/python-attribute-error-when-running-script-type-object-basecommand-has-no-att) seems pretty straightforward to fix, so I'd welcome a pull request.

**Comment by darkwizz** [comment]
ok, trying to fix it

**Comment by darkwizz** [comment]
created pull request #65

**Comment by chrisspen** [comment]
Thanks. I've merged your changes. I'll do some additional checks, and then publish it to PyPI in the next release.

**Comment by chrisspen** [comment]
This has now been published.
