### ISSUE TITLE
Extrange error

### ISSUE THREAD

**Issue by iesfausti** [chrisspen/django-chroniker#66]
Hi.
I got an error in a minimal 1.9 or 1.10 django project with a simple 'ls' command and a python 2.7
It works without jobs but when I add one...
TypeError: 'Queue' object is not callable
Did I forgot anything in the installation process?, seems really easy
I had to change line 69, but i dont know side-effects 
...force_run = None #stderr_queue('force_run', False)

Thanks in advance.

**Comment by chrisspen** [comment]
Can you provide the complete traceback?

**Comment by chrisspen** [comment]
Thanks. I'll try to reproduce and write a fix.

**Comment by chrisspen** [comment]
This has been fixed in the current release.

**Comment by iesfausti** [comment]
Thank you so much!
