### ISSUE TITLE
What about wiki, mm?

### ISSUE THREAD

**Issue by TatianaGaintseva** [chrisspen/django-chroniker#67]
I'm sorry, if it's not the right place to write about it, but:

I'd really like to use your extension, but, unfortunately, I didn't manage to find django admin parameters guide yet (in particular, I can't understand how to make jobs be performed not in every minute, but in different periods of time and what are "options" in admin job creation page?..)

If I'm mistaken and what I need lays somewhere next to me, please, tell me about it)

**Comment by sibuser** [comment]
Regarding intervals you set how often you would like a job to be executed and then add 'interval=<number>' as an parameter.
For example if you want to execute a job every 30 minutes just set frequency as 'minutely' and in the params field add 'interval=30'

**Comment by TatianaGaintseva** [comment]
Ok, That's great, thank you very much, but ndeed, what should I do if I want to understand how any other parameters\fields work? Is there any wiki or better readme?(

**Comment by sibuser** [comment]
Check this out http://labix.org/python-dateutil
Look at 'interval'.

**Comment by TatianaGaintseva** [comment]
Thank you very much for clarifying case with interval, I got it)I'm sorry for disturbing you, and you really helped meBut now I'm facing another problem with, it seems, google api: " l.byakov    [6:31 PM]  usage: manage.py [-h] [--auth_host_name AUTH_HOST_NAME][--noauth_local_webserver][--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]][--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]manage.py: error: unrecognized arguments: cronserver" Anyway, I'll try to fix it)17.11.2016, 18:33, "Alexey Ulyanov" <notifications@github.com>:Check this out http://labix.org/python-dateutil
Look at 'interval'.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




С уважением, Татьяна Гайнцева

**Comment by sibuser** [comment]
Actually you need to run it like this:
manage.py cron

**Comment by TatianaGaintseva** [comment]
Thank  you very much)
