### ISSUE TITLE
Cron Every other day

### ISSUE THREAD

**Issue by diegofcoelho** [chrisspen/django-chroniker#79]
Is it possible to set an alternated day cron task?
I didnt find how to save a */2 daily entry..

**Comment by chrisspen** [comment]
I use the dateutil library for this, which supports [RRules](https://labix.org/python-dateutil#head-1f7c5d0c956a96f26aa1de60b861f4d58180c1dd). I've never personally done every other day, but Google found me [this link](http://www.kanzaki.com/docs/ical/rrule.html) which shows how to do that.

**Comment by diegofcoelho** [comment]
Just to let you know that the way you coded to app made everything ridiculously easy.
To make an every-other-day task, you just set it as daily and add a interval: 2; in the RRules field.

Any possible interval can be set using given frequency and an interval. Congrats, buddy!

Cheers
