### ISSUE TITLE
Max Log Entries not respected

### ISSUE THREAD

**Issue by diegofcoelho** [chrisspen/django-chroniker#87]
All logs are kept until task entry is opened and saved. Otherwise, log entries will increase indefinitively.
No warning or error is triggered by Django.

![1](https://cloud.githubusercontent.com/assets/10437628/25309327/70d8b7ee-27a0-11e7-90bc-333f426e4552.PNG)

**Comment by diegofcoelho** [comment]
@chrisspen, problem around here still persists and I think is a mysql problem:

(1235, "This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'")

is the error thrown during debug.. You can set a minimum mysql version or try to set a compatibility solution.. I will try to get the version from the server connected to django.

Cheers

**Comment by chrisspen** [comment]
@diegofcoelho Yes, that bug was fixed in #90.

**Comment by diegofcoelho** [comment]
Sorry, did not check for an update! Thanks!
