### ISSUE TITLE
chroniker script is not running

### ISSUE THREAD

**Issue by Meenakshiithape** [chrisspen/django-chroniker#98]
I have try to set it with django 1.6.5 and python 2.7

python manage.py cron
command working properly, but when I try to execute

python D:\Python27\Scripts\chroniker -p D:\project_folder_mysite\
getting below error
ImportError: No module named chroniker

But job shows in running state on admin side, but not stopped.

Running job 1 1 - test - due.
1 Jobs are due.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python27\lib\multiprocessing\forking.py", line 373, in main
    prepare(preparation_data)
  File "D:\Python27\lib\multiprocessing\forking.py", line 482, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named chroniker
Process <JobProcess(1 - test - running, stopped[1])> ended.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
All jobs complete!

**Comment by chrisspen** [comment]
It looks like you're running it outside of the virtualenv where it's installed. Make sure you can run `manage.py shell` and import `chroniker`.
